<?php

/**
 * @file
 * Used to redirect standard twig templates to module twig templates.
 */

/**
 * Hook for processing information from the controller.
 *
 * Implements hook_theme().
 */
function abyss_theme($existing, $type, $theme, $path) {
  $theme = [
    'description' => [
      'variables' => [
        'fields' => [],
        'form' => [],
        'user' => [],
      ],
    ],
  ];

  $theme['page__abyss'] = [
    'base hook' => 'page',
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function abyss_theme_suggestions_paragraph(array $variables) {
  $suggestions = [];

  $suggestions[] = 'page__abyss';

  return $suggestions;
}
